export default {
  INIT_WITHDRAWAL: 'INIT_WITHDRAWAL',
  APPROVE_WITHDRAWAL: 'APPROVE_WITHDRAWAL',
  REJECT_WITHDRAWAL: 'REJECT_WITHDRAWAL',

  INIT_DIVORCE: 'INIT_DIVORCE',
  APPROVE_DIVORCE: 'APPROVE_DIVORCE',
  REJECT_DIVORCE: 'REJECT_DIVORCE',
};
