const APPROVE: 'APPROVE' = 'APPROVE';
const CREATE_TOKEN_CONTRACT: 'CREATE_TOKEN_CONTRACT' = 'CREATE_TOKEN_CONTRACT';
const CREATE_LOSTKEY_CONTRACT: 'CREATE_LOSTKEY_CONTRACT' = 'CREATE_LOSTKEY_CONTRACT';

export default {
  APPROVE,
  CREATE_TOKEN_CONTRACT,
  CREATE_LOSTKEY_CONTRACT,
};
