const APPROVE: 'APPROVE' = 'APPROVE';
const GET_CONTRACT_CREATION_PRICE: 'GET_CONTRACT_CREATION_PRICE' = 'GET_CONTRACT_CREATION_PRICE';
const CREATE_TOKEN_CONTRACT: 'CREATE_TOKEN_CONTRACT' = 'CREATE_TOKEN_CONTRACT';
const CREATE_LOSTKEY_CONTRACT: 'CREATE_LOSTKEY_CONTRACT' = 'CREATE_LOSTKEY_CONTRACT';
const CREATE_WILL_CONTRACT: 'CREATE_WILL_CONTRACT' = 'CREATE_WILL_CONTRACT';
const CREATE_CROWDSALE_CONTRACT: 'CREATE_CROWDSALE_CONTRACT' = 'CREATE_CROWDSALE_CONTRACT';

export default {
  APPROVE,
  GET_CONTRACT_CREATION_PRICE,
  CREATE_TOKEN_CONTRACT,
  CREATE_LOSTKEY_CONTRACT,
  CREATE_WILL_CONTRACT,
  CREATE_CROWDSALE_CONTRACT,
};
