export default {
  USER_AUTH_RESET_PASSWORD: 'USER_AUTH_RESET_PASSWORD',
  USER_AUTH_CONFIRM_RESET_PASSWORD: 'USER_AUTH_CONFIRM_RESET_PASSWORD',
  USER_AUTH_REGISTER_ACCOUNT: 'USER_AUTH_REGISTER_ACCOUNT',
  USER_AUTH_LOGOUT: 'USER_AUTH_LOGOUT',
};
